FROM python:3.10-slim

WORKDIR /app

COPY api/predict_api.py modelo_match_decision.joblib requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "predict_api:app", "--host", "0.0.0.0", "--port", "8000"]
